#!/bin/bash
 
if [ -z $1 ]; then
        echo "usage: clean-backups-instance-disk [instance-name]" ; exit 1
fi

_LIST=$(docker exec -it benji_app benji ls | grep $1 | awk '{print $4 "-" $2}' > /tmp/list)
LIST=$(cat /tmp/list)
options=($LIST)

menu() {
    echo "Avaliable backups:"
    for i in ${!options[@]}; do
        printf "%3d%s) %s\n" $((i+1)) "${choices[i]:- }" "${options[i]}"
    done
    [[ "$msg" ]] && echo "$msg"; :
}

prompt="Check an option (again to uncheck, ENTER when done): "
while menu && read -rp "$prompt" num && [[ "$num" ]]; do
    [[ "$num" != *[![:digit:]]* ]] &&
    (( num > 0 && num <= ${#options[@]} )) ||
    { msg="Invalid option: $num"; continue; }
    ((num--)); msg="${options[num]} was ${choices[num]:+un}checked"
    [[ "${choices[num]}" ]] && choices[num]="" || choices[num]="+"
done

for i in ${!options[@]}; do
SELECT=$([[ "${choices[i]}" ]]  && echo "${options[i]}");
echo $SELECT | awk 'NF' >> /tmp/run
done
echo ""
echo "The following backups for $1 will be deleted: "
cat /tmp/run
read -p "Are you sure you want to delete this backups ( YES or NO ): " ANSWER
if [ $ANSWER = YES ];
then
cat /tmp/run | cut -d '-' -f1,2,3 > /tmp/rm
sed -i 's/^/docker exec -it benji_app benji rm /g' /tmp/rm
sed -i 's/$/ --force/g' /tmp/rm
bash /tmp/rm
docker exec -it benji_app benji cleanup
if [ -f /tmp/run ];
then
rm /tmp/run
fi
if [ -f /tmp/rm ];
then
rm /tmp/rm
fi
else
if [ -f /tmp/run ];
then
rm /tmp/run
fi
if [ -f /tmp/rm ];
then
rm /tmp/rm
fi
exit 0
fi
